AllCops:
  DefaultFormatter: simple
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'lib/tasks/*'
    - 'db/**/*'
    - 'bin/*'
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/MutableConstant:
  Exclude:
    - 'app/models/searchable/*.rb'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact