source 'http://rubygems.org'

gem 'bcrypt'
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'redis', '~> 3.0'
gem 'sass-rails'
gem 'sprockets-rails'
gem 'turbolinks', '~> 5.0.0'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'bullet'
  gem 'dotenv-rails'
  gem 'image_optim_pack'
  gem 'web-console'
end

gem 'bootstrap', '~> 4.0.0'
gem 'font_assets'
gem 'friendly_id', '~> 5.1.0'
gem 'gretel'
gem 'haml-rails'
gem 'image_optim'
gem 'jquery-slick-rails'
gem 'jquery-ui-rails'
gem 'loadcss-rails', '~> 2.0.1'
gem 'mainsms_api'
gem 'meta-tags'
gem 'paperclip'
gem 'paperclip-compression'
gem 'paperclip-optimizer'
gem 'pg', '~> 0.21'
gem 'popper_js'
gem 'premailer-rails'
gem 'rack-canonical-host'
gem 'rubocop', '~> 0.52.1', require: false
gem 'russian'
gem 'sitemap_generator'
gem 'social-share-button'
gem 'sorcery'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'unicode'
gem 'will_paginate'
gem 'geocoder'
gem 'axlsx'
gem 'axlsx_rails'
gem 'rubyzip', '~> 0.9.9'

group :production do
  gem 'aws-sdk', '~> 1'
  gem 'aws-sdk-resources', '~> 2'
  gem 'aws-sdk-v1'
  gem 'heroku-deflater'
  gem 'image_optim_bin'
  gem 'rack-cors', require: 'rack/cors'
  gem 'rails_12factor'
end
